# Generated by Django 5.1 on 2024-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
