# Generated by Django 5.1 on 2024-08-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_points', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapppoints',
            name='task',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
